### ISSUE TITLE
Cannot find compatible Vulkan driver when opening Unreal in Remote Desktop Session

### ISSUE THREAD

**Issue by stephensamonte** [stephensamonte/server-personal#6]
Cannot find compatible Vulkan driver when opening Unreal in Remote Desktop Session.

"Cannot find a compatible Vulkan device or driver. Try updating your video driver to a more recent version and make sure your video card supports Vulkan. "

![image](https://user-images.githubusercontent.com/30998408/60759311-1b920580-9ff1-11e9-9397-07939d5cc860.png)

**Comment by stephensamonte** [comment]
The workstation now uses Windows 10 Education Edition rather than Linux.

**Comment by kminoda** [comment]
Hello. I got the same issue here. What do you mean by "The solution here is to remove the requirement of vulcan drivers" ? Would you mind telling me where to edit?

**Comment by stephensamonte** [comment]
@kminoda in the comment you're referring to, I meant that the accepted solution in the Unreal Engine Form ([Ubuntu 18.04 Cannot find a compatible Vulkan device or driver.](https://answers.unrealengine.com/questions/883700/ubuntu-1804-cannot-find-a-compatible-vulkan-device.html))

Was to use a flag that skipped the requirement:
![Screenshot_20200423-230636_Chrome](https://user-images.githubusercontent.com/30998408/80170928-27b67600-85b7-11ea-9dac-70ed256c6dae.jpg)

**Comment by kminoda** [comment]
I see, thank you!
So finally you didn't manage to use Unreal Engine running on remote Linux computer, right?

**Comment by stephensamonte** [comment]
I ended up using Unreal Engine on windows. There was less hassle. 

I think if you launch Unreal Engine locally on the Linux computer, then remote desktop to the Linux machine you will be able to use Unreal Engine that way.

**Comment by stephensamonte** [comment]
You could try to accessing the Linux machine via [Teamviewer](https://www.teamviewer.com/en-us/), [AnyDesk](https://anydesk.com/en), or [Chrome Remote Desktop](https://remotedesktop.google.com/). They access the local computer locally rather than creating a remote session. 

Let me know what you find out.

**Comment by stephensamonte** [comment]
@kminoda interesting. I'm not sure what else we could try. Please let me know if you find a good solution.

**Comment by stephensamonte** [comment]
"Trying to force OpenGL RHI but the project does not have it in TargetedRHIs list".

I found this: [Ubuntu Vulkan and OpenGL problems](https://answers.unrealengine.com/questions/936174/view.html)

You can add OpenGL back by uncommenting `GLSL_430` in `Engine/Config/BaseEngine.ini`.

**Comment by kochsebastian** [comment]
I have a similar problem. My Unreal Engine is installed on a linux machine and I want to access it via ssh -X from a windows machine and I get the vulcan driver error. Using the -opengl4 flag didn't solve the problem! Neither changing the .ini file!
